# Generated by Django 5.1.3 on 2024-11-17 01:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssistantAi', '0002_remove_userexercices_exercise_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercice',
            new_name='ExerciceModel',
        ),
    ]
